/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_massgrid_NativeSecp256k1 */

#ifndef _Included_org_massgrid_NativeSecp256k1
#define _Included_org_massgrid_NativeSecp256k1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_massgrid_NativeSecp256k1
 * Method:    secp256k1_ecdsa_verify
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_massgrid_NativeSecp256k1_secp256k1_1ecdsa_1verify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
