#!/bin/bash

# This is a thin wrapper around massgrid-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using massgrid-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_MASSGRIDD

# Grab the value of $REAL_MASSGRIDCLI which may be massgrid-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_MASSGRIDCLI}" "$@" | sed 's/\r//'
