#!/bin/bash

# This is a thin wrapper around mlgbcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using mlgbcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_MLGBCOIND

# Grab the value of $REAL_MLGBCOINCLI which may be mlgbcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_MLGBCOINCLI}" "$@" | sed 's/\r//'
